// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxodqqfrjfeesbtnswyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2RxcWZyamZlZXNidG5zd3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTY0NjIsImV4cCI6MjA2MTkzMjQ2Mn0.zzlMUAHT7dS-HVBIbwAiyeE7BKSBvNBPXprwpWT0alg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);